import React, { useState, useEffect } from 'react';
import RevealOnScroll from './RevealOnScroll';
import GlitchText from './GlitchText';

const journalLogs = [
    {
        id: 'log_01',
        title: 'FSAE Hydraulic Braking Design',
        subtitle: 'LOG_01 // VELOCE RACING GP // BRAKE BIAS & ROTOR ANALYSIS',
        date: '2018–2019',
        system: 'HYDRAULIC BRAKES',
        specs: [
            { label: 'PEAK PEDAL LOAD', value: '2000 N', status: 'SAFETY_PASS' },
            { label: 'CALCULATED DECEL', value: '3.33 m/s² (0.34g)', status: 'TELEMETRY_OK' },
            { label: 'BRAKING FORCE', value: '1665 N', status: 'SYS_NOMINAL' },
            { label: 'FRONT AXLE BIAS', value: '70% FORCE SHIFT', status: 'BIAS_CALIBRATED' }
        ],
        overview: 'Designing the closed-loop hydraulic brake circuit for a Formula Student open-wheel race car, optimizing dynamic braking force and rotor sizing based on kinetic energy dissipation.',
        sections: [
            {
                title: '1.1 The Vehicle Braking Architecture',
                content: `At Veloce Racing—the Formula Student team of the Vishwakarma Institute of Technology (VIT), Pune—I served as the Brake Systems Owner. The task was to design, size, package, and validate a high-performance, hydraulic-operated four-wheel braking system for our open-wheel single-seat race car.

The system was designed from the ground up to operate reliably under extreme track conditions. The architecture consists of a dual master cylinder system actuated by a single brake pedal through an adjustable balance bar (bias bar). High-pressure fluid is routed via steel-braided PTFE hoses to four custom disc brake assemblies, as mapped below:

- Brake Pedal: Actuated by the driver's foot, multiplying input force through mechanical leverage.
- Balance Bar: Splices the input force into two adjustable bias branches (Front and Rear).
- Dual Master Cylinders: Converts mechanical pushrod force into hydraulic fluid pressure (separate circuits for front and rear axles to prevent total system failure in case of a leak).
- High-Pressure PTFE Hoses: Transmits hydraulic pressure to the calipers.
- Calipers & Rotor Discs: Exerts clamping forces to generate friction torque against the wheels.`
            },
            {
                title: '1.2 Sizing, Deceleration Physics, and Sizing Calculations',
                content: `Formula Student regulations mandate strict safety boundaries:
1. Mechanical Strength: The brake pedal assembly must withstand a lateral load of 2000 N applied by the driver's foot without structural failure or triggering the engine shut-down fail-safe device.
2. Dynamic Performance: Under heavy braking, all four wheels must lock up simultaneously within a short stopping distance. Anti-lock Braking Systems (ABS) are prohibited.

To size the master cylinders, pedal leverage, and rotor diameters, I established a mathematical sizing pipeline using MATLAB/Simulink and Excel sheets.

Step-by-Step Deceleration Calculation:
To evaluate the minimum required braking force, we simulated stopping a 500 kg vehicle (including driver, fluids, and fuel) from 60 km/h to a complete stop in 5 seconds.

1. Deceleration (a):
   a = (v - u) / t = (16.67 m/s - 0 m/s) / 5 s = 3.33 m/s²
   In terms of g-force: Deceleration in g = 3.33 / 9.81 ≈ 0.34g

2. Total Braking Force Required (BF_total):
   F = m · a
   BF_total = 500 kg × 3.33 m/s² = 1665 N

Dynamic Weight Transfer:
Under deceleration, the Center of Gravity (CG) shifts load forward:
W_transfer = (Mass (m) × Deceleration (a) × Height of CG (h_cg)) / Wheelbase (L)

This dynamic shift unloads the rear axle and heavily loads the front axle. To prevent premature rear lockup (which induces vehicle instability), the brake force distribution must match this dynamic load. Based on our calculations, we calibrated the target brake force bias as:
- BF_front = 0.70 × BF_total (70% Front Bias)
- BF_rear = 0.30 × BF_total (30% Rear Bias)

Disc Rotor Sizing Equation:
The effective brake disc rotor radius (r_disc) was calculated by balancing the dynamic torque required to stop the wheel against the clamping force exerted by the calipers:

r_disc = (BF_wheel × R_tyre) / (F_clamp × μ_pad)

Where:
- BF_wheel: Braking force allocated per wheel.
- R_tyre: Tyre rolling radius.
- F_clamp: Caliper clamping force.
- μ_pad: Friction coefficient of the brake pads (assumed as 0.4).

The caliper clamping force itself is a function of the hydraulic pressure generated by the master cylinders:
P_hydraulic = (F_pedal × Mechanical Leverage) / A_mc
F_clamp = P_hydraulic × A_caliper × 2 (for double-sided caliper piston clamping)`
            },
            {
                title: '1.3 Key Engineering Innovations',
                content: `Innovation 1: Adjustable Brake Balance Bar (Bias Bar)
To allow real-time adjustments of the front-to-rear brake pressure bias based on driver preference and track grip levels, I designed a mechanical Brake Balance Bar.
- Mechanism: The balance bar consists of a threaded stud passing through a spherical bearing located inside the brake pedal pivot. Two yokes connect the outer ends of the bar to the pushrods of the front and rear master cylinders.
- Tuning: By rotating the central threaded stud, the spherical bearing shifts horizontally. This changes the moment arms from the pedal center to each master cylinder pushrod, altering the force distribution ratio.

Innovation 2: Horizontally Adjustable Pedal Box
Formula Student cars are driven by multiple team members of varying heights. To address this, I designed a sliding pedal box assembly:
- Feature: The entire pedal assembly (pedal, master cylinders, reservoir, and mounting brackets) was mounted on a slotted rail system.
- Benefit: Drivers could quickly adjust the pedal box horizontally, securing it via quick-release pins to accommodate different leg lengths while maintaining optimal biomechanical leverage.`
            },
            {
                title: '1.4 Rotor Thermal Stress FEA and Telemetry Validation',
                content: `Braking transforms kinetic energy into thermal energy. Under race conditions, rotors experience rapid temperature spikes leading to thermal stress, warping, or fading.

- FEA Analysis: I modeled the ventilated brake rotors in Hypermesh and performed transient thermal stress sweeps in ANSYS. This analysis helped define the optimal rotor thickness, ventilation channel geometry, and identify local heat hotspots.
- On-Field Verification: We installed surface thermocouples on the physical rotors and logged temperature profiles during track testing. The live telemetry data closely matched our thermal simulation boundaries, confirming the accuracy of our convective heat transfer coefficients.`
            }
        ]
    },
    {
        id: 'log_02',
        title: 'Forklift Sizing & Sourcing Sagas',
        subtitle: 'LOG_02 // TATA TECH GP // POWERTRAIN MATCHING & PUGH MATRICES',
        date: '2020–2022',
        system: 'POWERTRAIN INTEGRATION',
        specs: [
            { label: 'VEHICLE CAPACITY', value: '1.5T TO 3.0T', status: '70+ VARIANTS' },
            { label: 'MAX ENGINE POWER', value: '37 kW', status: 'EMISSION_TREM_IV' },
            { label: 'SIMULATION ENGINE', value: 'MATLAB / GT-SUITE', status: '2% MEAN ERROR' },
            { label: 'DECISION METHOD', value: 'WEIGHTED PUGH MATRIX', status: 'LEADERSHIP_SIGNOFF' }
        ],
        overview: 'Engineering the powertrain architecture for a new forklift lineup, creating a predictive mathematical model for torque converter matching and resolving sourcing debates via a Pugh Matrix.',
        sections: [
            {
                title: '2.1 Early Digital Engineering (2019–2020)',
                content: `My transition to Tata Technologies brought a massive shift in scale. Rather than a single prototype race car, I was now working on large-scale production platforms. My early assignments focused on digital mockups and automation for Jaguar Land Rover (JLR):

- VMockup Clash Analysis: Led clearance and interference audits for underhood components. I generated automated clearance reports to guarantee packaging envelopes were maintained under dynamic engine movement.
- Cooling Hose Routing: Managed CAD updates and routing layout designs for complex high-pressure coolant hoses, keeping them isolated from high-temperature exhaust paths.
- CATIA V5 Automation: Developed custom macros within CATIA V5 to automate the generation of hose paths, reduce CAD routing cycle times, and automatically calculate minimum bend radii to prevent kinking.`
            },
            {
                title: '2.2 Forklift Powertrain Development (2020–2022)',
                content: `In 2020, I was appointed the Powertrain System Owner (Senior Engineer) for a major material handling program developed for Godrej. The objective was to design and integrate the powertrain architecture for a new family of 1.5-tonne to 3-tonne capacity forklifts, spanning over 70 distinct variants (Eco/Premium, different fuel types, lifting heights, and transmission packages).

The Benchmarking & Requirements Phase:
We started by defining the target specification boundaries. I led the teardown and soft-benchmarking phase:
- Competitor Audit: Analyzed more than 10 competitor forklift platforms (evaluating market leaders and average market entrants) on performance parameters like acceleration, gradeability, fuel consumption, and cabin vibration.
- Voice of the Customer (VoC): Translated customer feedback gathered by the marketing and vehicle integration (VI) teams into engineering specifications.
- Sign-Off: Led the alignment and formal sign-off of the final product feature specification package with executive management.

Component Selection and Sourcing (RFI/RFQ):
Forklift powertrains consist of three coupled subsystems: Engine, Transmission, and Drive Axle. Because these are capital-intensive, supplier-proprietary parts, the challenge lies in choosing the optimal combination from Tier 1 suppliers.
- Engine Sizing: I established an engine power limit capped at a maximum of 37 kW to balance fuel efficiency, emission norms (BS-TREM IV compliance), and tractive requirements.
- Sourcing Campaigns: Floated Requests for Information (RFIs) and Requests for Quotations (RFQs) to global engine OEMs (including Tata Motors, Escorts, Simpsons, Cummins, Kubota) and major transmission/axle suppliers.`
            },
            {
                title: '2.3 Performance Simulation & Torque Matching',
                content: `With dozens of engines and transmissions on the table, finding the right match was an overwhelming permutation task. I developed a comprehensive Excel-based mathematical simulation model to predict vehicle tractive efforts.

Sizing & Simulation Workflow:
1. Inputs: Engine torque curves, torque converter performance curves (K-factor, torque ratio), 2-speed transmission ratios, axle ratios, tyre rolling radius, and vehicle weight.
2. Torque Converter Matching: Calculated engine-to-converter matching points to determine the actual torque multiplier at stall and throughout the vehicle speed range.
3. Outputs: Simulated maximum vehicle speed, maximum gradeability (laden and unladen), and acceleration times.

Tractive Effort (F_t) Sizing Equation:
F_t = (T_engine × T_R × η_trans × i_g × i_d) / R_tyre

Where:
- T_engine = Engine torque output at a given RPM.
- T_R = Torque converter torque ratio (dynamic multiplier).
- η_trans = Transmission mechanical efficiency.
- i_g = Gearbox ratio.
- i_d = Final drive (axle) ratio.

Model Validation:
We verified this spreadsheet simulator against full 1D system models built in GT-Suite and physical prototype testing. The model achieved a mean error of just 2%, streamlining our engineering sign-off pipeline.

Pugh Matrix Selection:
To finalize the supplier combinations, I utilized a Pugh Matrix weighing both objective parameters (cost, fuel economy, power density) and subjective parameters (service network strength, brand reputation, supplier reliability) on a 1 to 10 scale.`
            },
            {
                title: '2.4 Underhood Thermal Design and Air Flow Management',
                content: `Forklifts spend their lives operating at low speeds under high loads, often in poorly ventilated warehouses or hot dockyards. This makes thermal management a critical engineering bottleneck.

- 3D CFD Underhood Analysis: I performed underhood 3D Computational Fluid Dynamics (CFD) simulations to map velocity vectors and temperature gradients. This allowed us to locate recirculating hot air zones, design heat shields, and ensure sensitive components (like hoses and wiring harnesses) remained below their material degradation thresholds.
- 1D Cooling Simulation: Carried out 1D simulations of the radiator and hydraulic oil cooler package. We derived the maximum heat dissipation rates needed under worst-case ambient temperatures (up to 45°C).
- Fan Sizing and Duty Cycle: Evaluated engine-mounted mechanical fans, electric fans, and induction-motor-driven cooling fans. We selected the optimal fan blade geometry and flow characteristics while minimizing parasitic power draw from the engine.
- SAM Analysis: Conducted Serviceability, Accessibility, and Maintainability (SAM) audits on the cooling package to ensure coolant ports, oil filters, and fan belts could be serviced easily.`
            },
            {
                title: '2.5 IoT Telematics & Fleet Management Systems',
                content: `As industrial operations transitioned to smart warehouses, integrating connectivity into the forklift became a core program requirement. I co-engineered the software features and telematics interface that transformed the vehicle from a standalone lift into a connected fleet node.

Operator Security & Anti-Theft Systems:
- Fuel Cut-Off Interlocks: Designed an anti-theft system that controlled an electronic fuel-cut solenoid. The engine could only start if the driver entered a valid pin on the dashboard or scanned an authorized RFID badge, preventing unauthorized usage in shipyards and factories.
- Driver Presence Detection: Integrated safety seat-switches and seatbelt sensors. If the driver left the seat for more than 2 seconds, a safety controller neutralized the transmission and locked the hydraulic mast lift, preventing rollaway or tipping hazards.
- Control Input Calibration: Calibrated high-precision potentiometers for the electronic throttle and hydraulic joystick levers, mapping voltage swings to proportional valve commands.

Connected Fleet Telematics (IoT):
- CAN Bus Logging (SAE J1939): Configured the Telematics Control Unit (TCU) to listen to the vehicle's CAN bus. It logged parameters like engine RPM, transmission oil temperature, lift cycles, fuel level, and operating hours.
- Diagnostic Trouble Codes (DTCs): Defined custom diagnostic codes and warning thresholds (such as hydraulic temperature spikes or low system voltage) that immediately triggered telemetry alerts to warehouse management portals.
- Store-and-Forward Data Resiliency: Sizable warehouses have cellular dead zones. We designed a local storage buffer in the TCU's flash memory. When network connection was lost, telemetry packets were cached and automatically uploaded once connection was restored or synced to a technician's mobile app via Bluetooth.`
            },
            {
                title: '2.6 Prototype Validation and Supplier Collaboration',
                content: `The culmination of the forklift project was the assembly and testing of physical prototypes.

- The Flywheel Matching Challenge: During assembly, we encountered a critical mismatch between the engine flywheel interface and the input shaft of the selected Powershift transmission. I worked closely with the engine supplier, leading the design modifications of the flywheel coupler. This collaborative effort resolved the alignment issue without delaying the prototype build schedule.
- Design Verification Plan (DVP): I participated in the physical verification tests on test tracks, validating Tractive Effort (maximum drawbar pull and gradeability), Thermal Performance (heat balance tests of coolant, transmission oil, and hydraulic oil), Vibration (seat/mount accelerometers), and Exhaust system backpressures.
- The Design Standard: To capture these engineering lessons, I wrote a comprehensive technical design guide: "Forklift Power Systems Designs". This standard was distributed to Godrej engineers to serve as the blueprint for future forklift platform developments.`
            }
        ]
    }
];

const Journal = () => {
    const [activeLogIdx, setActiveLogIdx] = useState(0);
    const [hoveredLogIdx, setHoveredLogIdx] = useState(null);

    const activeLog = journalLogs[activeLogIdx];

    // Auto-scroll to top of console when active log changes
    useEffect(() => {
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }, [activeLogIdx]);

    const styles = {
        pageWrapper: {
            background: 'var(--color-bg)',
            minHeight: 'calc(100vh - var(--nav-height))',
            paddingTop: 'var(--nav-height)',
            paddingBottom: '80px',
        },
        container: {
            maxWidth: '1200px',
            margin: '0 auto',
            padding: '0 20px',
        },
        backHeader: {
            display: 'flex',
            alignItems: 'center',
            gap: '10px',
            marginBottom: '40px',
            fontFamily: 'var(--font-mono)',
            fontSize: '0.85rem',
            color: 'var(--color-primary)',
            cursor: 'pointer',
            textTransform: 'uppercase',
            fontWeight: 'bold',
            width: 'fit-content',
            transition: 'color 0.2s ease',
        },
        dashboardLayout: {
            display: 'grid',
            gridTemplateColumns: '350px 1fr',
            gap: '40px',
        },
        sidebar: {
            display: 'flex',
            flexDirection: 'column',
            gap: '20px',
        },
        logCard: (isActive, isHovered) => ({
            background: isActive ? 'var(--color-surface)' : 'rgba(255, 255, 255, 0.02)',
            border: `1px solid ${isActive ? 'var(--color-primary)' : (isHovered ? 'rgba(255,255,255,0.1)' : 'rgba(255,255,255,0.03)')}`,
            borderLeft: `5px solid ${isActive ? 'var(--color-primary)' : 'rgba(255,255,255,0.08)'}`,
            padding: '20px',
            borderRadius: '2px',
            cursor: 'pointer',
            transition: 'all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1)',
            transform: isHovered ? 'translateY(-2px)' : 'translateY(0)',
            boxShadow: isActive ? '0 10px 20px var(--color-primary-dim)' : 'none',
        }),
        logCode: {
            fontFamily: 'var(--font-mono)',
            fontSize: '0.75rem',
            color: 'var(--color-secondary)',
            fontWeight: 'bold',
            marginBottom: '6px',
            display: 'block',
        },
        logTitle: {
            fontFamily: 'var(--font-display)',
            fontSize: '1rem',
            color: '#fff',
            marginBottom: '8px',
        },
        logMeta: {
            display: 'flex',
            justifyContent: 'space-between',
            fontFamily: 'var(--font-mono)',
            fontSize: '0.75rem',
            color: 'var(--color-text-muted)',
        },
        mainConsole: {
            background: 'var(--color-surface)',
            border: '1px solid rgba(255, 255, 255, 0.04)',
            borderRadius: '4px',
            padding: '35px',
            display: 'flex',
            flexDirection: 'column',
            gap: '35px',
            boxShadow: '0 15px 35px rgba(0,0,0,0.3)',
        },
        consoleHeader: {
            borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
            paddingBottom: '20px',
        },
        consoleSub: {
            fontFamily: 'var(--font-mono)',
            fontSize: '0.8rem',
            color: 'var(--color-text-muted)',
            letterSpacing: '1px',
            display: 'block',
            marginBottom: '6px',
        },
        consoleTitle: {
            fontSize: '1.8rem',
            fontFamily: 'var(--font-display)',
            color: '#fff',
            lineHeight: 1.2,
        },
        hudGrid: {
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
            gap: '15px',
        },
        hudBox: {
            background: '#0e1014',
            borderLeft: '3px solid var(--color-secondary)',
            padding: '12px 18px',
            borderRadius: '2px',
        },
        hudLabel: {
            fontFamily: 'var(--font-mono)',
            fontSize: '0.7rem',
            color: 'var(--color-text-muted)',
            textTransform: 'uppercase',
            display: 'block',
            marginBottom: '4px',
        },
        hudValue: {
            fontFamily: 'var(--font-mono)',
            fontSize: '0.9rem',
            color: '#fff',
            fontWeight: 'bold',
            display: 'block',
            marginBottom: '4px',
        },
        hudStatus: {
            fontFamily: 'var(--font-mono)',
            fontSize: '0.65rem',
            color: 'var(--color-secondary)',
            display: 'flex',
            alignItems: 'center',
            gap: '5px',
        },
        contentSection: {
            display: 'flex',
            flexDirection: 'column',
            gap: '30px',
        },
        sectionBlock: {
            background: 'rgba(255, 255, 255, 0.01)',
            border: '1px solid rgba(255, 255, 255, 0.02)',
            padding: '25px',
            borderRadius: '2px',
        },
        sectionTitle: {
            fontFamily: 'var(--font-mono)',
            fontSize: '0.9rem',
            color: 'var(--color-primary)',
            letterSpacing: '1px',
            fontWeight: 'bold',
            marginBottom: '15px',
            borderBottom: '1px dashed rgba(255, 255, 255, 0.05)',
            paddingBottom: '10px',
        },
        sectionText: {
            color: 'var(--color-text-muted)',
            fontSize: '0.92rem',
            lineHeight: 1.7,
            whiteSpace: 'pre-wrap',
        }
    };

    const handleBackClick = () => {
        window.location.hash = '#projects';
    };

    return (
        <div style={styles.pageWrapper}>
            <div style={styles.container}>
                {/* Standalone Header Navigation */}
                <div 
                    style={styles.backHeader} 
                    onClick={handleBackClick}
                    className="link-hover"
                >
                    <i className="fa-solid fa-arrow-left"></i>
                    <span>← RETURN TO PADDOCK (MAIN SITE)</span>
                </div>

                <RevealOnScroll>
                    <div style={{ marginBottom: '50px' }}>
                        <h2 className="section-title" style={{ borderLeftWidth: '5px' }}>
                            <GlitchText text="TELEMETRY JOURNAL" />
                            <span style={{ fontSize: '0.5em', color: 'var(--color-text-muted)' }}> // SYSTEMS DEBRIEF REPORTS</span>
                        </h2>
                        <p style={{ color: 'var(--color-text-muted)', maxWidth: '800px', fontSize: '0.95rem', lineHeight: 1.5 }}>
                            Welcome to the telemetry logs. These reports contain complete architectural breakdowns, sizing calculations, physics equations, and validation details transcribed directly from my field engineering journal.
                        </p>
                    </div>
                </RevealOnScroll>

                <div className="journal-dashboard" style={styles.dashboardLayout}>
                    {/* Left Panel: Log Selector */}
                    <div style={styles.sidebar}>
                        <div style={{ fontFamily: 'var(--font-display)', fontSize: '0.8rem', color: '#fff', letterSpacing: '2px', marginBottom: '10px' }}>
                            SELECT DEBRIEF ARCHIVE
                        </div>
                        {journalLogs.map((log, idx) => {
                            const isActive = activeLogIdx === idx;
                            const isHovered = hoveredLogIdx === idx;
                            return (
                                <div
                                    key={log.id}
                                    style={styles.logCard(isActive, isHovered)}
                                    onMouseEnter={() => setHoveredLogIdx(idx)}
                                    onMouseLeave={() => setHoveredLogIdx(null)}
                                    onClick={() => setActiveLogIdx(idx)}
                                >
                                    <span style={styles.logCode}>
                                        {isActive ? '● ' : ''}LOG_0{idx + 1} // ACTIVE_SECTOR
                                    </span>
                                    <h3 style={styles.logTitle}>{log.title}</h3>
                                    <div style={styles.logMeta}>
                                        <span>SYSTEM: {log.system}</span>
                                        <span>{log.date}</span>
                                    </div>
                                </div>
                            );
                        })}

                        {/* F1 HUD Decal Box */}
                        <div style={{
                            background: '#0e1014',
                            padding: '20px',
                            border: '1px solid rgba(255,255,255,0.02)',
                            borderRadius: '2px',
                            fontFamily: 'var(--font-mono)',
                            fontSize: '0.75rem',
                            color: 'var(--color-text-muted)',
                            display: 'flex',
                            flexDirection: 'column',
                            gap: '8px',
                            marginTop: '20px',
                        }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                <span>LOG_STATUS</span>
                                <span style={{ color: 'var(--color-secondary)' }}>ONLINE</span>
                            </div>
                            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                <span>FORMAT</span>
                                <span>UNABRIDGED TECHNICAL</span>
                            </div>
                            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                <span>EQUATIONS</span>
                                <span>LATEX / ISO STANDARD</span>
                            </div>
                            <div style={{ borderTop: '1px dashed rgba(255,255,255,0.05)', margin: '5px 0' }} />
                            <div style={{ fontSize: '0.7rem', color: '#666', lineHeight: 1.3 }}>
                                Note: Technical values and formulas are synchronized with simulation outputs from MATLAB/Simulink and ANSYS.
                            </div>
                        </div>
                    </div>

                    {/* Right Panel: Active Console View */}
                    <div style={styles.mainConsole} className="journal-console">
                        <div style={styles.consoleHeader}>
                            <span style={styles.consoleSub}>{activeLog.subtitle}</span>
                            <h2 style={styles.consoleTitle}>{activeLog.title}</h2>
                            <p style={{ color: 'var(--color-text-muted)', marginTop: '12px', fontSize: '0.95rem', lineHeight: 1.6 }}>
                                {activeLog.overview}
                            </p>
                        </div>

                        {/* Telemetry HUD Mini-Grid */}
                        <div style={styles.hudGrid}>
                            {activeLog.specs.map((spec, sIdx) => (
                                <div key={sIdx} style={styles.hudBox}>
                                    <span style={styles.hudLabel}>{spec.label}</span>
                                    <span style={styles.hudValue}>{spec.value}</span>
                                    <span style={styles.hudStatus}>
                                        <span className="f1-led-light f1-led-green" style={{ width: '5px', height: '5px' }} />
                                        {spec.status}
                                    </span>
                                </div>
                            ))}
                        </div>

                        {/* Content Blocks */}
                        <div style={styles.contentSection}>
                            {activeLog.sections.map((sect, sIdx) => (
                                <div key={sIdx} style={styles.sectionBlock} className="journal-section-card">
                                    <h4 style={styles.sectionTitle}>{sect.title}</h4>
                                    <p style={styles.sectionText}>{sect.content}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
            
            {/* Responsiveness Overrides */}
            <style>{`
                @media screen and (max-width: 992px) {
                    .journal-dashboard {
                        grid-template-columns: 1fr !important;
                    }
                }
            `}</style>
        </div>
    );
};

export default Journal;
