import React, { useState, useEffect } from 'react';
import RevealOnScroll from './RevealOnScroll';
import GlitchText from './GlitchText';

const journalLogs = [
    {
        id: 'log_01',
        title: 'FSAE Hydraulic Braking Design',
        subtitle: 'LOG_01 // VELOCE RACING GP // BRAKE BIAS & ROTOR ANALYSIS',
        date: '2018–2019',
        system: 'HYDRAULIC BRAKES',
        specs: [
            { label: 'PEAK PEDAL LOAD', value: '2000 N', status: 'SAFETY_PASS' },
            { label: 'CALCULATED DECEL', value: '3.33 m/s² (0.34g)', status: 'TELEMETRY_OK' },
            { label: 'BRAKING FORCE', value: '1665 N', status: 'SYS_NOMINAL' },
            { label: 'FRONT AXLE BIAS', value: '70% FORCE SHIFT', status: 'BIAS_CALIBRATED' }
        ],
        overview: 'Designing the closed-loop hydraulic brake circuit for a Formula Student open-wheel race car, optimizing dynamic braking force and rotor sizing based on kinetic energy dissipation.',
        sections: [
            {
                title: '1.1 The Vehicle Braking Architecture',
                content: `At Veloce Racing—the Formula Student team of the Vishwakarma Institute of Technology (VIT), Pune—I served as the Brake Systems Owner. The task was to design, size, package, and validate a high-performance, hydraulic-operated four-wheel braking system for our open-wheel single-seat race car.

The system was designed from the ground up to operate reliably under extreme track conditions. The architecture consists of a dual master cylinder system actuated by a single brake pedal through an adjustable balance bar (bias bar). High-pressure fluid is routed via steel-braided PTFE hoses to four custom disc brake assemblies, as mapped below:

- Brake Pedal: Actuated by the driver's foot, multiplying input force through mechanical leverage.
- Balance Bar: Splices the input force into two adjustable bias branches (Front and Rear).
- Dual Master Cylinders: Converts mechanical pushrod force into hydraulic fluid pressure (separate circuits for front and rear axles to prevent total system failure in case of a leak).
- High-Pressure PTFE Hoses: Transmits hydraulic pressure to the calipers.
- Calipers & Rotor Discs: Exerts clamping forces to generate friction torque against the wheels.`
            },
            {
                title: '1.2 Sizing, Deceleration Physics, and Sizing Calculations',
                content: `Formula Student regulations mandate strict safety boundaries:
1. Mechanical Strength: The brake pedal assembly must withstand a lateral load of 2000 N applied by the driver's foot without structural failure or triggering the engine shut-down fail-safe device.
2. Dynamic Performance: Under heavy braking, all four wheels must lock up simultaneously within a short stopping distance. Anti-lock Braking Systems (ABS) are prohibited.

To size the master cylinders, pedal leverage, and rotor diameters, I established a mathematical sizing pipeline using MATLAB/Simulink and Excel sheets.

Step-by-Step Deceleration Calculation:
To evaluate the minimum required braking force, we simulated stopping a 500 kg vehicle (including driver, fluids, and fuel) from 60 km/h to a complete stop in 5 seconds.

1. Deceleration (a):
   a = (v - u) / t = (16.67 m/s - 0 m/s) / 5 s = 3.33 m/s²
   In terms of g-force: Deceleration in g = 3.33 / 9.81 ≈ 0.34g

2. Total Braking Force Required (BF_total):
   F = m · a
   BF_total = 500 kg × 3.33 m/s² = 1665 N

Dynamic Weight Transfer:
Under deceleration, the Center of Gravity (CG) shifts load forward:
W_transfer = (Mass (m) × Deceleration (a) × Height of CG (h_cg)) / Wheelbase (L)

This dynamic shift unloads the rear axle and heavily loads the front axle. To prevent premature rear lockup (which induces vehicle instability), the brake force distribution must match this dynamic load. Based on our calculations, we calibrated the target brake force bias as:
- BF_front = 0.70 × BF_total (70% Front Bias)
- BF_rear = 0.30 × BF_total (30% Rear Bias)

Disc Rotor Sizing Equation:
The effective brake disc rotor radius (r_disc) was calculated by balancing the dynamic torque required to stop the wheel against the clamping force exerted by the calipers:

r_disc = (BF_wheel × R_tyre) / (F_clamp × μ_pad)

Where:
- BF_wheel: Braking force allocated per wheel.
- R_tyre: Tyre rolling radius.
- F_clamp: Caliper clamping force.
- μ_pad: Friction coefficient of the brake pads (assumed as 0.4).

The caliper clamping force itself is a function of the hydraulic pressure generated by the master cylinders:
P_hydraulic = (F_pedal × Mechanical Leverage) / A_mc
F_clamp = P_hydraulic × A_caliper × 2 (for double-sided caliper piston clamping)`
            },
            {
                title: '1.3 Key Engineering Innovations',
                content: `Innovation 1: Adjustable Brake Balance Bar (Bias Bar)
To allow real-time adjustments of the front-to-rear brake pressure bias based on driver preference and track grip levels, I designed a mechanical Brake Balance Bar.
- Mechanism: The balance bar consists of a threaded stud passing through a spherical bearing located inside the brake pedal pivot. Two yokes connect the outer ends of the bar to the pushrods of the front and rear master cylinders.
- Tuning: By rotating the central threaded stud, the spherical bearing shifts horizontally. This changes the moment arms from the pedal center to each master cylinder pushrod, altering the force distribution ratio.

Innovation 2: Horizontally Adjustable Pedal Box
Formula Student cars are driven by multiple team members of varying heights. To address this, I designed a sliding pedal box assembly:
- Feature: The entire pedal assembly (pedal, master cylinders, reservoir, and mounting brackets) was mounted on a slotted rail system.
- Benefit: Drivers could quickly adjust the pedal box horizontally, securing it via quick-release pins to accommodate different leg lengths while maintaining optimal biomechanical leverage.`
            },
            {
                title: '1.4 Rotor Thermal Stress FEA and Telemetry Validation',
                content: `Braking transforms kinetic energy into thermal energy. Under race conditions, rotors experience rapid temperature spikes leading to thermal stress, warping, or fading.

- FEA Analysis: I modeled the ventilated brake rotors in Hypermesh and performed transient thermal stress sweeps in ANSYS. This analysis helped define the optimal rotor thickness, ventilation channel geometry, and identify local heat hotspots.
- On-Field Verification: We installed surface thermocouples on the physical rotors and logged temperature profiles during track testing. The live telemetry data closely matched our thermal simulation boundaries, confirming the accuracy of our convective heat transfer coefficients.`
            }
        ]
    },
    {
        id: 'log_02',
        title: 'Forklift Sizing & Sourcing Sagas',
        subtitle: 'LOG_02 // TATA TECH GP // POWERTRAIN MATCHING & PUGH MATRICES',
        date: '2020–2022',
        system: 'POWERTRAIN INTEGRATION',
        specs: [
            { label: 'VEHICLE CAPACITY', value: '1.5T TO 3.0T', status: '70+ VARIANTS' },
            { label: 'MAX ENGINE POWER', value: '37 kW', status: 'EMISSION_TREM_IV' },
            { label: 'SIMULATION ENGINE', value: 'MATLAB / GT-SUITE', status: '2% MEAN ERROR' },
            { label: 'DECISION METHOD', value: 'WEIGHTED PUGH MATRIX', status: 'LEADERSHIP_SIGNOFF' }
        ],
        overview: 'Engineering the powertrain architecture for a new forklift lineup, creating a predictive mathematical model for torque converter matching and resolving sourcing debates via a Pugh Matrix.',
        sections: [
            {
                title: '2.1 Early Digital Engineering (2019–2020)',
                content: `My transition to Tata Technologies brought a massive shift in scale. Rather than a single prototype race car, I was now working on large-scale production platforms. My early assignments focused on digital mockups and automation for Jaguar Land Rover (JLR):

- VMockup Clash Analysis: Led clearance and interference audits for underhood components. I generated automated clearance reports to guarantee packaging envelopes were maintained under dynamic engine movement.
- Cooling Hose Routing: Managed CAD updates and routing layout designs for complex high-pressure coolant hoses, keeping them isolated from high-temperature exhaust paths.
- CATIA V5 Automation: Developed custom macros within CATIA V5 to automate the generation of hose paths, reduce CAD routing cycle times, and automatically calculate minimum bend radii to prevent kinking.`
            },
            {
                title: '2.2 Forklift Powertrain Development (2020–2022)',
                content: `In 2020, I was appointed the Powertrain System Owner (Senior Engineer) for a major material handling program developed for Godrej. The objective was to design and integrate the powertrain architecture for a new family of 1.5-tonne to 3-tonne capacity forklifts, spanning over 70 distinct variants (Eco/Premium, different fuel types, lifting heights, and transmission packages).

The Benchmarking & Requirements Phase:
We started by defining the target specification boundaries. I led the teardown and soft-benchmarking phase:
- Competitor Audit: Analyzed more than 10 competitor forklift platforms (evaluating market leaders and average market entrants) on performance parameters like acceleration, gradeability, fuel consumption, and cabin vibration.
- Voice of the Customer (VoC): Translated customer feedback gathered by the marketing and vehicle integration (VI) teams into engineering specifications.
- Sign-Off: Led the alignment and formal sign-off of the final product feature specification package with executive management.

Component Selection and Sourcing (RFI/RFQ):
Forklift powertrains consist of three coupled subsystems: Engine, Transmission, and Drive Axle. Because these are capital-intensive, supplier-proprietary parts, the challenge lies in choosing the optimal combination from Tier 1 suppliers.
- Engine Sizing: I established an engine power limit capped at a maximum of 37 kW to balance fuel efficiency, emission norms (BS-TREM IV compliance), and tractive requirements.
- Sourcing Campaigns: Floated Requests for Information (RFIs) and Requests for Quotations (RFQs) to global engine OEMs (including Tata Motors, Escorts, Simpsons, Cummins, Kubota) and major transmission/axle suppliers.`
            },
            {
                title: '2.3 Performance Simulation & Torque Matching',
                content: `With dozens of engines and transmissions on the table, finding the right match was an overwhelming permutation task. I developed a comprehensive Excel-based mathematical simulation model to predict vehicle tractive efforts.

Sizing & Simulation Workflow:
1. Inputs: Engine torque curves, torque converter performance curves (K-factor, torque ratio), 2-speed transmission ratios, axle ratios, tyre rolling radius, and vehicle weight.
2. Torque Converter Matching: Calculated engine-to-converter matching points to determine the actual torque multiplier at stall and throughout the vehicle speed range.
3. Outputs: Simulated maximum vehicle speed, maximum gradeability (laden and unladen), and acceleration times.

Tractive Effort (F_t) Sizing Equation:
F_t = (T_engine × T_R × η_trans × i_g × i_d) / R_tyre

Where:
- T_engine = Engine torque output at a given RPM.
- T_R = Torque converter torque ratio (dynamic multiplier).
- η_trans = Transmission mechanical efficiency.
- i_g = Gearbox ratio.
- i_d = Final drive (axle) ratio.

Model Validation:
We verified this spreadsheet simulator against full 1D system models built in GT-Suite and physical prototype testing. The model achieved a mean error of just 2%, streamlining our engineering sign-off pipeline.

Pugh Matrix Selection:
To finalize the supplier combinations, I utilized a Pugh Matrix weighing both objective parameters (cost, fuel economy, power density) and subjective parameters (service network strength, brand reputation, supplier reliability) on a 1 to 10 scale.`
            },
            {
                title: '2.4 Underhood Thermal Design and Air Flow Management',
                content: `Forklifts spend their lives operating at low speeds under high loads, often in poorly ventilated warehouses or hot dockyards. This makes thermal management a critical engineering bottleneck.

- 3D CFD Underhood Analysis: I performed underhood 3D Computational Fluid Dynamics (CFD) simulations to map velocity vectors and temperature gradients. This allowed us to locate recirculating hot air zones, design heat shields, and ensure sensitive components (like hoses and wiring harnesses) remained below their material degradation thresholds.
- 1D Cooling Simulation: Carried out 1D simulations of the radiator and hydraulic oil cooler package. We derived the maximum heat dissipation rates needed under worst-case ambient temperatures (up to 45°C).
- Fan Sizing and Duty Cycle: Evaluated engine-mounted mechanical fans, electric fans, and induction-motor-driven cooling fans. We selected the optimal fan blade geometry and flow characteristics while minimizing parasitic power draw from the engine.
- SAM Analysis: Conducted Serviceability, Accessibility, and Maintainability (SAM) audits on the cooling package to ensure coolant ports, oil filters, and fan belts could be serviced easily.`
            },
            {
                title: '2.5 IoT Telematics & Fleet Management Systems',
                content: `As industrial operations transitioned to smart warehouses, integrating connectivity into the forklift became a core program requirement. I co-engineered the software features and telematics interface that transformed the vehicle from a standalone lift into a connected fleet node.

Operator Security & Anti-Theft Systems:
- Fuel Cut-Off Interlocks: Designed an anti-theft system that controlled an electronic fuel-cut solenoid. The engine could only start if the driver entered a valid pin on the dashboard or scanned an authorized RFID badge, preventing unauthorized usage in shipyards and factories.
- Driver Presence Detection: Integrated safety seat-switches and seatbelt sensors. If the driver left the seat for more than 2 seconds, a safety controller neutralized the transmission and locked the hydraulic mast lift, preventing rollaway or tipping hazards.
- Control Input Calibration: Calibrated high-precision potentiometers for the electronic throttle and hydraulic joystick levers, mapping voltage swings to proportional valve commands.

Connected Fleet Telematics (IoT):
- CAN Bus Logging (SAE J1939): Configured the Telematics Control Unit (TCU) to listen to the vehicle's CAN bus. It logged parameters like engine RPM, transmission oil temperature, lift cycles, fuel level, and operating hours.
- Diagnostic Trouble Codes (DTCs): Defined custom diagnostic codes and warning thresholds (such as hydraulic temperature spikes or low system voltage) that immediately triggered telemetry alerts to warehouse management portals.
- Store-and-Forward Data Resiliency: Sizable warehouses have cellular dead zones. We designed a local storage buffer in the TCU's flash memory. When network connection was lost, telemetry packets were cached and automatically uploaded once connection was restored or synced to a technician's mobile app via Bluetooth.`
            },
            {
                title: '2.6 Prototype Validation and Supplier Collaboration',
                content: `The culmination of the forklift project was the assembly and testing of physical prototypes.

- The Flywheel Matching Challenge: During assembly, we encountered a critical mismatch between the engine flywheel interface and the input shaft of the selected Powershift transmission. I worked closely with the engine supplier, leading the design modifications of the flywheel coupler. This collaborative effort resolved the alignment issue without delaying the prototype build schedule.
- Design Verification Plan (DVP): I participated in the physical verification tests on test tracks, validating Tractive Effort (maximum drawbar pull and gradeability), Thermal Performance (heat balance tests of coolant, transmission oil, and hydraulic oil), Vibration (seat/mount accelerometers), and Exhaust system backpressures.
- The Design Standard: To capture these engineering lessons, I wrote a comprehensive technical design guide: "Forklift Power Systems Designs". This standard was distributed to Godrej engineers to serve as the blueprint for future forklift platform developments.`
            }
        ]
    },
    {
        id: 'log_03',
        title: 'M&M Powertrain & EV Cooling',
        subtitle: 'LOG_03 // MAHINDRA GP // THERMAL CFD & ASIL SAFETY CASE',
        date: '2022–2023',
        system: 'THERMAL SYSTEMS',
        specs: [
            { label: 'ROLE & TEAM', value: 'OWNER // 2 ENG', status: 'LEAD_ROLE' },
            { label: 'HEAT REJECTION', value: 'U · A · ΔT_LMTD', status: 'SIZING_OK' },
            { label: 'VP0 BUILD ISSUES', value: '15+ RESOLVED', status: '8D_CHAMPION' },
            { label: 'SAFETY CASE', value: 'ISO 26262 ASIL-C', status: 'HOMOLOGATED' }
        ],
        overview: 'Architecting powertrain cooling and EV thermal management systems, running 3D CFD airflow simulations and wind tunnel validations, and driving ASIL-C safety cases through production gateways.',
        sections: [
            {
                title: '3.1 Powertrain Cooling Systems & Component Sizing',
                content: `Transitioning to Mahindra & Mahindra’s Commercial Vehicle department as an Assistant Manager, I was appointed the primary owner of the vehicle cooling systems. In this role, I demonstrated strong team leadership by managing a team of 2 engineers, delegating design tasks, setting milestone targets, and orchestrating cross-functional collaboration between simulation, sourcing, quality, and prototype assembly teams to clear critical gateways on schedule.

I had complete responsibility for the cooling system architecture from concept (mule vehicle design) through physical validation to mass production. Leveraging my 3D CAD proficiency (utilizing CATIA V5), I designed complex packaging layouts under the hood, routing high-pressure coolant lines and packaging thermal modules within highly constrained engine bay envelopes.

Furthermore, I directed the creation of production-ready 2D manufacturing drawings incorporating strict Geometric Dimensioning and Tolerancing (GD&T) and tolerance stack-up analyses. Releasing these designs through PLM systems (such as Siemens Teamcenter) ensured flawless fitment, minimized assembly variations, and facilitated supplier onboarding and tooling signoff for radiator and intercooler assemblies.

The scope covered the complete thermal architecture, requiring the custom design, sizing, and packaging of:
- Radiators: Sizing the active surface area and core thickness to dissipate high thermal loads.
- Intercoolers: Optimizing charge-air cooling density to ensure peak volumetric combustion efficiency.
- Expansion Tanks: Sizing fluid capacities and pressure cap thresholds to handle system degas and thermal expansion cycles.
- Coolant Hose Routing: Optimizing routing envelopes under the hood to ensure thermal isolation and prevent hose kinking.

The Heat Rejection Sizing Equation:
To size the radiator core area (A), I established a physics-based sizing framework utilizing the Logarithmic Mean Temperature Difference (LMTD) method:
Q_reject = U · A · ΔT_LMTD

Where:
- U is the Overall Heat Transfer Coefficient, combining fluid-side and air-side convective boundary layers.
- A is the total effective surface area of the radiator fins and tubes.
- ΔT_LMTD is the Logarithmic Mean Temperature Difference.`
            },
            {
                title: '3.2 Underhood Thermal Simulation & Wind Tunnel Validation',
                content: `To bridge the gap between virtual concepts and real-world hardware, I deployed a hybrid validation pipeline combining 1D system modeling, 3D CFD, and aerodynamic wind tunnel testing.

- 1D Thermal Modeling: I tuned transient vehicle thermal models in GT-Suite to size cooling components and optimize coolant flow distributions across various engine operating maps.
- 3D CFD Underhood Analysis: I executed 3D Computational Fluid Dynamics (CFD) simulations to analyze velocity vectors and temperature profiles in the engine bay. This analysis allowed us to pinpoint recirculation zones—areas where hot exhaust air was drawn back into the radiator—and design targeted deflectors and heat shields to isolate temperature-sensitive electronics.
- Wind Tunnel and Field Trials: I led physical validation trials, preparing high-density thermocouple grids and hot-wire anemometer rigs on prototype vehicles. Dictating test cases inside aerodynamic wind tunnels, I gathered real-time thermal telemetry logs. This data allowed us to calibrate our virtual CFD boundary conditions, achieving a closed-loop correlation within a tight error margin.`
            },
            {
                title: '3.3 Functional Safety (ISO 26262), Quality Gateways & VP0/VP1 Milestones',
                content: `Automotive production requires strict adherence to quality and safety standards. Throughout the product development lifecycle, I managed deliverables across the APQP framework, driving Design Failure Mode and Effects Analysis (DFMEA) workshops and PPAP documentation.

ISO 26262 Functional Safety:
I owned the functional safety engineering safety case for the Accelerator Pedal Module. This critical system was designed and validated in compliance with ISO 26262 functional safety requirements, achieving ASIL-C safety goal sign-off.
- HARA (Hazard Analysis and Risk Assessment): Analyzed vehicle-level hazards (e.g., unintended acceleration) to define safety goals and safe states.
- DFMEA & Mechanical Integrity: Led design reviews focusing on sensor redundancy (dual-sensor pedal designs) and structural integrity of the pedal arm (injection-molded polymer analysis) to prevent structural failures.

VP0/VP1 Prototype Issue Resolution:
During the initial VP0 (Validation Prototype 0) vehicle build, we encountered numerous clearance, static packaging, and hose kinking issues. I structured a systematic 8D (Eight Disciplines) problem-solving pipeline to investigate and resolve these assembly issues. By analyzing hose bend radii and dynamic engine movements, we modified mounting bracket geometries to prevent material fatigue. I resolved over 15 high-priority design bottlenecks before the VP1 build, ensuring the program cleared its quality gateways on time. For this achievement, I was awarded the title of VP0 Build Issue Resolution Champion.`
            },
            {
                title: '3.4 EV Cooling & Active Thermal Management Integration',
                content: `As Mahindra expanded its footprint into electric mobility, I contributed to the design and development of thermal systems for Electric Vehicle (EV) powertrains.

- EV Component Sizing: Performed 1D sizing calculations for Low-Temperature Radiators (LTR) to cool electrical powertrains (inverters and traction motors) and manage battery pack temperature envelopes.
- 5-Way Electric Coolant Valve Integration: I defined the system specifications for a 5-way rotary electric coolant valve. This valve dynamically routes coolant in serial, parallel, or bypass configurations, enabling active battery heating/cooling and recovery of e-motor waste heat to improve cabin HVAC efficiency.
- CAN/LIN Integration: Co-engineered the communication interface between temperature sensors, the thermal controller, and the Battery Management System (BMS) over CAN and LIN buses.
- DTC Definition: Documented Diagnostic Trouble Codes (DTCs) and OBD requirements for thermal actuator faults, ensuring safety compliance in electric drivetrains.`
            }
        ]
    },
    {
        id: 'log_04',
        title: 'EV Range & Powerflow Algorithms',
        subtitle: 'LOG_04 // COGNIZANT GP // MBSE & PATENTED ESTIMATION ALGORITHMS',
        date: '2023–Present',
        system: 'EV CONTROLS',
        specs: [
            { label: 'PLATFORM REACH', value: 'NA & EU PROGRAMS', status: 'STLA_BRAIN' },
            { label: 'ALGORITHM DESIGN', value: 'SOCR & RANGE ESTIMATOR', status: 'EURO_7_COMPLIANT' },
            { label: 'PATENT FILED', value: 'INVENTION RECORD (IDR)', status: 'LOW_FLUCTUATION' },
            { label: 'SYSML ENGINE', value: 'RHAPSODY / CAMEO', status: 'MBSE_TRACEABLE' }
        ],
        overview: 'Feature owner for EV Range and Powerflow estimation algorithms at Stellantis, designing low-fluctuation predictive range filters, deploying SysML-based MBSE architectures, and integrating ADAS torque requests.',
        sections: [
            {
                title: '4.1 Enterprise Systems Engineering & Model-Based Systems Engineering (MBSE)',
                content: `Joining Cognizant as a Senior Systems Consultant, I was embedded in a dedicated profile supporting Stellantis' global vehicle programs (covering North American and European platforms). In this role, I served as the Systems Engineer / Feature Owner for EV Range and Powerflow, managing system-level requirements and E/E architecture integration from early concepts to production.

Requirements Engineering & ASPICE Compliance:
I authored high-integrity system and feature specification packages in IBM Rational DOORS / DOORS Next Gen. All requirements engineering and verification activities were conducted in strict compliance with ASPICE (Automotive SPICE) guidelines, specifically adhering to the SYS.1 to SYS.5 (System Engineering) and SWE.1 to SWE.6 (Software Engineering) process models. By establishing rigorous bi-directional traceability matrices, I linked high-level stakeholder requests down to system specifications, software architecture elements, Simulink models, and physical verification test cases, guaranteeing maximum compliance throughout the V-Cycle.

Model-Based Systems Engineering (MBSE) & AUTOSAR Integration:
To manage the complexity of modern software-defined vehicles, I deployed MBSE methodologies inside the design pipeline:
- SysML Architecture Modeling: Designed functional architectures and interface contracts in IBM Rational Rhapsody and CATIA Magic (Cameo Systems Modeler).
- Interface Design & ASW-BSW Mapping: Created Block Definition Diagrams (BDD) and Internal Block Diagrams (IBD) to define port configurations and signal flows between the powertrain control module, battery management system, and cabin HMI. Leveraging my knowledge of Classic and Adaptive AUTOSAR standards, I mapped Application Software (ASW) runnables to Basic Software (BSW) services, defining Software Component (SWC) descriptions, Run-Time Environment (RTE) events, and diagnostic service mappings.
- Control Function Prototyping: Translated functional SysML models into executable control algorithms within MATLAB/Simulink to simulate behavior prior to target ECU compilation.`
            },
            {
                title: '4.2 Advanced Range Estimation Algorithms & IDR Innovation',
                content: `The core of my engineering responsibility at Stellantis is the development and validation of the EV Range Estimation (Distance-to-Empty) algorithm.

Physics of Range Estimation:
The range estimation algorithm dynamically predicts the remaining driving distance based on battery state and current driving conditions:
Range = (E_battery × SOC × η_powertrain) / EC_dynamic

Where:
- E_battery is the total battery pack energy capacity (kWh).
- SOC is the State of Charge (%).
- η_powertrain is the dynamic powertrain efficiency (electrical to mechanical).
- EC_dynamic is the filtered dynamic energy consumption rate (Wh/km).

The IDR Innovation:
Standard range estimation algorithms suffer from significant fluctuations, causing driver anxiety. To solve this, I designed a predictive filtering algorithm and filed an Invention Disclosure Record (IDR).

The patented algorithm integrates:
1. Dynamic Range Mapping: Adjusting calculations in real time based on historical driving styles.
2. EV Routing Integration: Communicating with navigation systems to incorporate upcoming route gradients, speed limits, and traffic conditions into the energy model.
3. Range Impact Calculations: Determining the real-time energy drain of auxiliary systems (like cabin heating, seat heaters, and battery cooling) to calculate their impact on battery capacity.

This system stabilizes the range estimation, filtering out transient spikes to deliver a smooth and predictable display on the driver's screen.`
            },
            {
                title: '4.3 Powerflow Systems Feature Owner — Energy Calculations & HMI',
                content: `As the Systems Feature Owner for the EV Powerflow visualization feature, I was responsible for the end-to-end systems definition, requirements engineering, and interface design. I defined the mathematical framework, signal routing paths, and HMI display requirements for real-time power balance calculations, helping drivers optimize energy consumption via the dashboard's real-time Powerflow Visualization.

Power Balance Equation:
The algorithm calculates the instantaneous power balance across the vehicle:
P_battery = P_motor + P_engine + P_grey - P_regen

Where:
- P_battery is the net battery electrical power.
- P_motor is the electrical power consumed by the traction motors.
- P_engine is the generator/ICE power output (for hybrid configurations).
- P_grey represents Grey Power—the sum of all low-voltage and auxiliary power drains (HVAC compressor, cabin heaters, electric power steering, DCDC converter, and coolant pumps).
- P_regen is the electrical power recovered through regenerative braking.

Signal Filtering and Euro 7 Compliance:
The raw electrical power signals from vehicle sensors are highly noisy due to transient current swings. I developed digital low-pass and Kalman filters to smooth the signals before they are rendered on the HMI.

Additionally, I supported development of the State of Certified Range (SOCR) algorithm, a new requirement under Euro 7 regulations. The SOCR monitors and records battery capacity degradation over time to ensure compliance with lifetime range guarantees.`
            },
            {
                title: '4.4 Drive Mode Management, Vehicle Securement, & ADAS Torque Integration',
                content: `A key systems integration challenge was aligning driver assistance features, securement states, and drive mode selections with powertrain torque requests.

- Drive Mode Management: I engineered the system requirements and control logic for the vehicle's Drive Mode Management system. This involved designing the dynamic torque mapping and mode transition logic across multiple driver-selectable modes (such as Eco, Sport, Comfort, and All-Terrain configurations). Sized and calibrated torque request envelopes to optimize responsiveness and energy efficiency dynamically based on battery SOC, thermal boundaries, and axle telemetry.
- Vehicle Securement: Led safety logic and software interlocks for the Vehicle Securement systems. Authored requirements for rollaway prevention, automatic Electronic Parking Brake (EPB) engagement/release, and secure vehicle state machines (managing automatic transitions to safe-park states when door status, seatbelt, or key-off events indicated the driver left the vehicle).
- Functional Safety (ISO 26262) & ASIL-D Calibration: Owned and validated critical safety goals for torque management and securement systems. Under the ISO 26262 functional safety standard, these control paths carried safety goals rated up to ASIL-D. Participated in Hazard Analysis and Risk Assessment (HARA), drafted Functional and Technical Safety Requirements (FSR/TSR), and designed safety mechanisms like torque-neutral safe states.
- ADAS Requirements & Torque Interface: Authored system-level requirements, functional safety specifications, and interface control documents (ICDs) for ADAS functions (such as Adaptive Cruise Control and Active Emergency Braking) and their torque arbitration logic with the propulsion controller's Base Torque Management module, ensuring safety-critical requirements were defined for smooth torque transitions.
- Network Communication Protocols (C-CAN to CAN FD): Managed network signal mapping and interface configurations, coordinating the system-level vehicle network transition from legacy C-CAN to high-speed CAN FD communications, as well as routing parameters over LIN and Automotive Ethernet.
- Controls & Calibration Support (HIL Testing): Supported controls development and calibration engineering teams by executing Hardware-in-the-Loop (HIL) validation testing, utilizing Vector CANoe and ETAS INCA to trace vehicle network signals, debug interfaces, and verify calibration parameter datasets against systems requirements.
- Stellantis Architectures: Deployed and validated these systems across Stellantis' next-generation electrical and physical architectures: STLA Brain, STLA Large, STLA Frame, Atlantis High, and Atlantis Mid.`
            },
            {
                title: '4.5 Engineering Innovations & Development Tooling',
                content: `To fast-track E/E systems engineering and requirements verification cycles across global platforms, I developed several custom internal software utilities and engineering innovations:

1. AI Requirements Classifier (INCOSE Guidelines): An intelligent semantic parser using LLMs to automatically classify, syntax-check, and audit system requirements in DOORS according to INCOSE (International Council on Systems Engineering) rules, accelerating requirements quality reviews.
2. Advanced DBC Visualizer: A specialized diagnostic and mapping interface tool that decodes CAN/CAN FD database files (DBC) and visualizes multiplexed signals, bus layouts, and PDU configurations to simplify port definitions.
3. CFTS Macrovariant Development Tool: A scripting framework that automates the generation and configuration of Component Functional Technical Specification (CFTS) macro-variants, reducing manual parameter mapping errors.
4. Advanced Signal Data Analysis Tool: A Python-based processing engine to automate post-processing of HIL and road test telemetry logs, automatically aligning sensor streams and identifying signal anomalies.`
            }
        ]
    }
];

const Journal = () => {
    const [activeLogIdx, setActiveLogIdx] = useState(0);
    const [hoveredLogIdx, setHoveredLogIdx] = useState(null);

    const activeLog = journalLogs[activeLogIdx];

    // Auto-scroll to top of console when active log changes
    useEffect(() => {
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }, [activeLogIdx]);

    const styles = {
        pageWrapper: {
            background: 'var(--color-bg)',
            minHeight: 'calc(100vh - var(--nav-height))',
            paddingTop: 'var(--nav-height)',
            paddingBottom: '80px',
        },
        container: {
            maxWidth: '1200px',
            margin: '0 auto',
            padding: '0 20px',
        },
        backHeader: {
            display: 'flex',
            alignItems: 'center',
            gap: '10px',
            marginBottom: '40px',
            fontFamily: 'var(--font-mono)',
            fontSize: '0.85rem',
            color: 'var(--color-primary)',
            cursor: 'pointer',
            textTransform: 'uppercase',
            fontWeight: 'bold',
            width: 'fit-content',
            transition: 'color 0.2s ease',
        },
        dashboardLayout: {
            display: 'grid',
            gridTemplateColumns: '350px 1fr',
            gap: '40px',
        },
        sidebar: {
            display: 'flex',
            flexDirection: 'column',
            gap: '20px',
        },
        logCard: (isActive, isHovered) => ({
            background: isActive ? 'var(--color-surface)' : 'rgba(255, 255, 255, 0.02)',
            border: `1px solid ${isActive ? 'var(--color-primary)' : (isHovered ? 'rgba(255,255,255,0.1)' : 'rgba(255,255,255,0.03)')}`,
            borderLeft: `5px solid ${isActive ? 'var(--color-primary)' : 'rgba(255,255,255,0.08)'}`,
            padding: '20px',
            borderRadius: '2px',
            cursor: 'pointer',
            transition: 'all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1)',
            transform: isHovered ? 'translateY(-2px)' : 'translateY(0)',
            boxShadow: isActive ? '0 10px 20px var(--color-primary-dim)' : 'none',
        }),
        logCode: {
            fontFamily: 'var(--font-mono)',
            fontSize: '0.75rem',
            color: 'var(--color-secondary)',
            fontWeight: 'bold',
            marginBottom: '6px',
            display: 'block',
        },
        logTitle: {
            fontFamily: 'var(--font-display)',
            fontSize: '1rem',
            color: '#fff',
            marginBottom: '8px',
        },
        logMeta: {
            display: 'flex',
            justifyContent: 'space-between',
            fontFamily: 'var(--font-mono)',
            fontSize: '0.75rem',
            color: 'var(--color-text-muted)',
        },
        mainConsole: {
            background: 'var(--color-surface)',
            border: '1px solid rgba(255, 255, 255, 0.04)',
            borderRadius: '4px',
            padding: '35px',
            display: 'flex',
            flexDirection: 'column',
            gap: '35px',
            boxShadow: '0 15px 35px rgba(0,0,0,0.3)',
        },
        consoleHeader: {
            borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
            paddingBottom: '20px',
        },
        consoleSub: {
            fontFamily: 'var(--font-mono)',
            fontSize: '0.8rem',
            color: 'var(--color-text-muted)',
            letterSpacing: '1px',
            display: 'block',
            marginBottom: '6px',
        },
        consoleTitle: {
            fontSize: '1.8rem',
            fontFamily: 'var(--font-display)',
            color: '#fff',
            lineHeight: 1.2,
        },
        hudGrid: {
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
            gap: '15px',
        },
        hudBox: {
            background: '#0e1014',
            borderLeft: '3px solid var(--color-secondary)',
            padding: '12px 18px',
            borderRadius: '2px',
        },
        hudLabel: {
            fontFamily: 'var(--font-mono)',
            fontSize: '0.7rem',
            color: 'var(--color-text-muted)',
            textTransform: 'uppercase',
            display: 'block',
            marginBottom: '4px',
        },
        hudValue: {
            fontFamily: 'var(--font-mono)',
            fontSize: '0.9rem',
            color: '#fff',
            fontWeight: 'bold',
            display: 'block',
            marginBottom: '4px',
        },
        hudStatus: {
            fontFamily: 'var(--font-mono)',
            fontSize: '0.65rem',
            color: 'var(--color-secondary)',
            display: 'flex',
            alignItems: 'center',
            gap: '5px',
        },
        contentSection: {
            display: 'flex',
            flexDirection: 'column',
            gap: '30px',
        },
        sectionBlock: {
            background: 'rgba(255, 255, 255, 0.01)',
            border: '1px solid rgba(255, 255, 255, 0.02)',
            padding: '25px',
            borderRadius: '2px',
        },
        sectionTitle: {
            fontFamily: 'var(--font-mono)',
            fontSize: '0.9rem',
            color: 'var(--color-primary)',
            letterSpacing: '1px',
            fontWeight: 'bold',
            marginBottom: '15px',
            borderBottom: '1px dashed rgba(255, 255, 255, 0.05)',
            paddingBottom: '10px',
        },
        sectionText: {
            color: 'var(--color-text-muted)',
            fontSize: '0.92rem',
            lineHeight: 1.7,
            whiteSpace: 'pre-wrap',
        }
    };

    const handleBackClick = () => {
        window.location.hash = '#projects';
    };

    return (
        <div style={styles.pageWrapper}>
            <div style={styles.container}>
                {/* Standalone Header Navigation */}
                <div 
                    style={styles.backHeader} 
                    onClick={handleBackClick}
                    className="link-hover"
                >
                    <i className="fa-solid fa-arrow-left"></i>
                    <span>← RETURN TO PADDOCK (MAIN SITE)</span>
                </div>

                <RevealOnScroll>
                    <div style={{ marginBottom: '50px' }}>
                        <h2 className="section-title" style={{ borderLeftWidth: '5px' }}>
                            <GlitchText text="TELEMETRY JOURNAL" />
                            <span style={{ fontSize: '0.5em', color: 'var(--color-text-muted)' }}> // SYSTEMS DEBRIEF REPORTS</span>
                        </h2>
                        <p style={{ color: 'var(--color-text-muted)', maxWidth: '800px', fontSize: '0.95rem', lineHeight: 1.5 }}>
                            Welcome to the telemetry logs. These reports contain complete architectural breakdowns, sizing calculations, physics equations, and validation details transcribed directly from my field engineering journal.
                        </p>
                    </div>
                </RevealOnScroll>

                <div className="journal-dashboard" style={styles.dashboardLayout}>
                    {/* Left Panel: Log Selector */}
                    <div style={styles.sidebar}>
                        <div style={{ fontFamily: 'var(--font-display)', fontSize: '0.8rem', color: '#fff', letterSpacing: '2px', marginBottom: '10px' }}>
                            SELECT DEBRIEF ARCHIVE
                        </div>
                        {journalLogs.map((log, idx) => {
                            const isActive = activeLogIdx === idx;
                            const isHovered = hoveredLogIdx === idx;
                            return (
                                <div
                                    key={log.id}
                                    style={styles.logCard(isActive, isHovered)}
                                    onMouseEnter={() => setHoveredLogIdx(idx)}
                                    onMouseLeave={() => setHoveredLogIdx(null)}
                                    onClick={() => setActiveLogIdx(idx)}
                                >
                                    <span style={styles.logCode}>
                                        {isActive ? '● ' : ''}LOG_0{idx + 1} // ACTIVE_SECTOR
                                    </span>
                                    <h3 style={styles.logTitle}>{log.title}</h3>
                                    <div style={styles.logMeta}>
                                        <span>SYSTEM: {log.system}</span>
                                        <span>{log.date}</span>
                                    </div>
                                </div>
                            );
                        })}

                        {/* F1 HUD Decal Box */}
                        <div style={{
                            background: '#0e1014',
                            padding: '20px',
                            border: '1px solid rgba(255,255,255,0.02)',
                            borderRadius: '2px',
                            fontFamily: 'var(--font-mono)',
                            fontSize: '0.75rem',
                            color: 'var(--color-text-muted)',
                            display: 'flex',
                            flexDirection: 'column',
                            gap: '8px',
                            marginTop: '20px',
                        }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                <span>LOG_STATUS</span>
                                <span style={{ color: 'var(--color-secondary)' }}>ONLINE</span>
                            </div>
                            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                <span>FORMAT</span>
                                <span>UNABRIDGED TECHNICAL</span>
                            </div>
                            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                <span>EQUATIONS</span>
                                <span>LATEX / ISO STANDARD</span>
                            </div>
                            <div style={{ borderTop: '1px dashed rgba(255,255,255,0.05)', margin: '5px 0' }} />
                            <div style={{ fontSize: '0.7rem', color: '#666', lineHeight: 1.3 }}>
                                Note: Technical values and formulas are synchronized with simulation outputs from MATLAB/Simulink and ANSYS.
                            </div>
                        </div>
                    </div>

                    {/* Right Panel: Active Console View */}
                    <div style={styles.mainConsole} className="journal-console">
                        <div style={styles.consoleHeader}>
                            <span style={styles.consoleSub}>{activeLog.subtitle}</span>
                            <h2 style={styles.consoleTitle}>{activeLog.title}</h2>
                            <p style={{ color: 'var(--color-text-muted)', marginTop: '12px', fontSize: '0.95rem', lineHeight: 1.6 }}>
                                {activeLog.overview}
                            </p>
                        </div>

                        {/* Telemetry HUD Mini-Grid */}
                        <div style={styles.hudGrid}>
                            {activeLog.specs.map((spec, sIdx) => (
                                <div key={sIdx} style={styles.hudBox}>
                                    <span style={styles.hudLabel}>{spec.label}</span>
                                    <span style={styles.hudValue}>{spec.value}</span>
                                    <span style={styles.hudStatus}>
                                        <span className="f1-led-light f1-led-green" style={{ width: '5px', height: '5px' }} />
                                        {spec.status}
                                    </span>
                                </div>
                            ))}
                        </div>

                        {/* Content Blocks */}
                        <div style={styles.contentSection}>
                            {activeLog.sections.map((sect, sIdx) => (
                                <div key={sIdx} style={styles.sectionBlock} className="journal-section-card">
                                    <h4 style={styles.sectionTitle}>{sect.title}</h4>
                                    <p style={styles.sectionText}>{sect.content}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
            
            {/* Responsiveness Overrides */}
            <style>{`
                @media screen and (max-width: 992px) {
                    .journal-dashboard {
                        grid-template-columns: 1fr !important;
                    }
                }
            `}</style>
        </div>
    );
};

export default Journal;
